Adding a guide for testing with CI/CD systems
luckyframework/website pull request #283
Opened 2020-04-15 00:11 UTC by arschles

Fixes luckyframework/lucky#1077

2020-04-15 01:14 UTC, jwoertink requested changes
Awesome! I think this will be a huge bonus. I know a lot of people prefer setting these up. I just have a few small changes, but overall I think this is the right direction.

2020-04-15 01:14 UTC, jwoertink commented on src/actions/guides/testing/ci-cd.cr
> +class Guides::Testing::Introduction < GuideAction
This class name should be `Guides::Testing::ContinuousIntegration` or something like that. We have an `Introduction` class already.

2020-04-15 01:14 UTC, jwoertink commented on src/actions/guides/testing/ci-cd.cr
> +        - [Travis CI](https://travis-ci.org/) - The `lucky` CLI
Since you mention that Lucky generates this just below, maybe we can leave it off of this spot?

2020-04-15 01:14 UTC, jwoertink commented on src/actions/guides/testing/ci-cd.cr
> +        that platform, congratulatioins! You're done.
How about something like:

> Lucky generates the TravisCI config file for you when you create your app.

But you're not really done at that point, right? Or are you? I don't really know how that works. Does github just sync those up when you have that config file?

2020-04-15 01:14 UTC, jwoertink commented on src/actions/guides/testing/ci-cd.cr
> +  end
spacing here.

2020-10-01 16:33 UTC, stephendolan commented
@jwoertink Do you think this is worth re-opening at this point?

2020-10-01 16:40 UTC, jwoertink commented
Yeah, I think it would be cool to have section dedicated to getting setup with a CI where we could give a quick example on travis, circle, and github actions. This PR was a decent start, but just needed a few quick changes. @stephendolan if you wanted to open a different PR with your take on it, I'm open to that. We're almost 6 months stale on this now.

2020-10-01 16:53 UTC, stephendolan commented
Cool, opened #439 to track on this.

2020-10-16 16:38 UTC, stephendolan commented
Since this is pretty stale, closing so that we have it as a reference for the resolution of #439 but can get a fresh take on it now that we're in a GitHub Actions kind of world.

2020-10-16 16:38 UTC, closed without merging

2020-11-06 21:02 UTC, arschles commented
Sorry I left this for so long everyone. I don't think I'm going to be able to contribute on this addition at the moment but I work for Microsoft and I'm happy to help get actions working. Feel free to ping me

2020-11-06 21:06 UTC, jwoertink commented
Hey no worries @arschles. We appreciate you getting this started! It's definitely something we want. 👍