Add section for `empty_tag`
luckyframework/website pull request #324
Opened 2020-06-10 13:02 UTC by richarddewit

And a note in the `link` section for rendering `<link>` elements in the `<head>`

2020-06-10 13:12 UTC, richarddewit commented
What did I break?

2020-06-10 15:36 UTC, paulcsmith reviewed
2 tiny suggestions. Thanks so much for documenting this! We've got a few new tag helpers coming in the next version for handling canonical links but this is great to have since there are *lots* of ways to use empty tags!

2020-06-10 15:36 UTC, paulcsmith commented on src/actions/guides/frontend/rendering_html.cr
> +    If there's a tag you would like to render, but there is no helper for it, then use `empty_tag`.
```suggestion
    If there's a bodyless tag you would like to render, but there is no helper for it, then use `empty_tag`.
```

2020-06-10 15:36 UTC, paulcsmith commented on src/actions/guides/frontend/rendering_html.cr
> +      meta name: "theme-color", content: "#c0ffee"
I think this can be removed since it doesn't seem to apply to the `empty_tag` documentation

```suggestion
```

2020-06-10 15:37 UTC, paulcsmith commented
And no worries about CI. I don't think you broke anything. I think it is something with webpack acting up for who knows why. I'll look into it

2020-06-10 15:44 UTC, jwoertink requested changes
I'm surprised we didn't already have a section mentioning the `empty_tag` method. Thanks for adding this. Just a few small changes and it should be good.

2020-06-10 15:44 UTC, jwoertink commented on src/actions/guides/frontend/rendering_html.cr
> +    If there's a tag you would like to render, but there is no helper for it, then use `empty_tag`.
This isn't really correct. The `empty_tag` is for creating tags that don't take a block like `<link>`. `<img>`, `<br>`, `<hr>`, etc.... For tags that do take a block, you would use the `tag()` method.

2020-06-10 15:44 UTC, jwoertink commented on src/actions/guides/frontend/rendering_html.cr
> +    empty_tag "link", rel: "canonical", href: "https://example.com/some/canonical/url"
Now that we have a helper method merged in, this section can go away. We can add docs on using that in another PR.

2020-06-10 15:44 UTC, jwoertink commented on src/actions/guides/frontend/rendering_html.cr
> +    This is especially convenient for elements with varying attributes, like a set of favicons:
👍

2020-06-10 15:44 UTC, jwoertink commented on src/actions/guides/frontend/rendering_html.cr
> +    > NOTE: If you are looking for a way to create `link` tags in the `<head>`, use the [`empty_tag` helper](##{ANCHOR_EMPTY_TAG}).
```suggestion
    > NOTE: If you are looking for a way to create `<link>` tags in the `<head>`, use the [`empty_tag` helper](##{ANCHOR_EMPTY_TAG}).
```

2020-06-11 00:04 UTC, paulcsmith approved these changes

2020-06-11 00:04 UTC, paulcsmith commented
Looks great! Thank you :D

2020-06-11 00:04 UTC, merged