Add note about using base validation. Slight re-org
luckyframework/website pull request #701
Opened 2021-07-01 14:40 UTC by paulcsmith

2021-07-01 14:43 UTC, stephendolan approved these changes
Nice!

2021-07-01 15:00 UTC, jwoertink reviewed
Nice! Just left a few comments, but this definitely makes it a bit more clear 😄

2021-07-01 15:00 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +    You can customize a DeleteOperations with callbacks and validations.  These
```suggestion
    You can customize DeleteOperations with callbacks and validations.  These
```

2021-07-01 15:00 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +            html Servers::EditPage, server: server
The only thing with this is if the record is soft deleted, the `server` wouldn't know that, but the `deleted_server` would.

2021-07-01 15:01 UTC, paulcsmith commented on src/actions/guides/database/deleting_records.cr
> +    You can customize a DeleteOperations with callbacks and validations.  These
Nice catch!

2021-07-01 15:21 UTC, paulcsmith commented on src/actions/guides/database/deleting_records.cr
> +            html Servers::EditPage, server: server
Ohhh, I didn't read about the new `soft_delete` changes. Will make those changes and re-ping for review later. Thanks! I would not have caught that :P

2021-07-01 15:21 UTC, paulcsmith commented on src/actions/guides/database/deleting_records.cr
> +            html Servers::EditPage, server: server
Oh wait, can you do `operation.soft_deleted?` if so then that could work instead of using the `deleted_server`?

2021-07-01 15:24 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +            html Servers::EditPage, server: server
No. `operation.deleted?` will return `true` if the record was soft deleted though.

2021-07-01 15:43 UTC, paulcsmith commented on src/actions/guides/database/deleting_records.cr
> +            html Servers::EditPage, server: server
Ah ok so you don't need the returned serve if you use `operation.deleted?` if so I'll document that. That way you don't need to use the second block arg in most (not all) cases.

2021-07-01 16:00 UTC, jwoertink approved these changes
Feel free to merge when ready!

2021-07-24 18:12 UTC, jwoertink commented
Gonna need a rebase here

2022-02-25 16:28 UTC, jwoertink requested changes
@stephendolan not sure if you were wrapping this up or not, but there's a few more changes that are still missing. Just since we've renamed the method and such since this was originally pushed up.

2022-02-25 16:28 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +            flash.danger = "Could not delete"
```suggestion
            flash.failure = "Could not delete"
```

The valid methods are `success`, `failure`, and `info`.

2022-02-25 16:28 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +        # It is shown here with a `_` to show that it can be used if needed.
Though, this is true, it doesn't fit in this case because in the `else` branch, the 2nd arg is used.

2022-02-25 16:28 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +        DeleteServer.delete(server) do |operation, _deleted_server|
```suggestion
        DeleteServer.delete(server) do |operation, deleted_server|
```

Since both variables are used.

2022-02-25 16:28 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +    Server::DeleteOperation.destroy!(server)
```suggestion
    Server::DeleteOperation.delete!(server)
```

2022-02-25 18:59 UTC, stephendolan commented
@jwoertink Yeah, just trying to close this out to clear the website PR queue :)

2022-02-25 19:15 UTC, jwoertink requested changes
Ok, I missed these last time, but I think that's all of them!

2022-02-25 19:15 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +    DeleteServer.destroy!(server)
```suggestion
    DeleteServer.delete!(server)
```

2022-02-25 19:15 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +    ### Destroy and raise if it fails
```suggestion
    ### Delete and raise if it fails
```

2022-02-25 19:15 UTC, jwoertink commented on src/actions/guides/database/deleting_records.cr
> +    You can also use the `destroy!` method if you don't need validations and expect delete's to work every time:
```suggestion
    You can also use the `delete!` method if you don't need validations and expect deletes to work every time:
```

2022-02-25 19:29 UTC, jwoertink approved these changes
sweet :+1:  Thanks for doing that @stephendolan

2022-02-25 19:29 UTC, merged