Update guides to use LuckyEnv
luckyframework/website pull request #707
Opened 2021-07-06 15:44 UTC by kevinsjoberg

Updates the guides to make use of `LuckyEnv` instead of `Lucky::Env`. See https://github.com/luckyframework/lucky_cli/pull/655 for details.

2021-07-08 21:29 UTC, stephendolan commented
@kevinsjoberg Thanks so much for submitting this! If you can fix that one failing test, this looks good to merge!

2021-07-08 21:37 UTC, kevinsjoberg commented
@stephendolan oh, totally missed that. Thanks for reminding me. 🙂 I've amended the original commit.

2021-07-09 15:24 UTC, jwoertink commented
I didn't look it up, but does 0.27.2 generate Lucky apps with LuckyEnv built in? If it does, then we should be fine. If not, then we need to wait until 0.28 drops before merging this.

2021-07-24 15:07 UTC, jwoertink requested changes
I think just the syntax for highlighting consistency, and then we're good to merge! Thanks for doing this.

2021-07-24 15:07 UTC, jwoertink commented on src/actions/guides/getting-started/configuration.cr
> +    ```
```suggestion
    ```crystal
```

2021-07-24 15:12 UTC, kevinsjoberg commented on src/actions/guides/getting-started/configuration.cr
> +    ```
Great suggestion. 👍

2021-07-24 15:25 UTC, jwoertink approved these changes
sweet!

2021-07-24 15:26 UTC, merged